### ISSUE TITLE
Deletion errors

### ISSUE THREAD

**Issue by greatbooms** [ddworken/hishtory#108]
hi

I have been using this program with great appreciation.

However, due to this glitch, when I delete it, I keep getting the following message.

```_hishtory_precmd:8: command not found: hishtory```

It doesn't seem to be deleting perfectly and I would like you to check this issue.

Thank you.

**Comment by ddworken** [comment]
Thanks for opening this issue! Can you share some more details about what exactly triggers this behavior? Do you mean that you tried to delete the CLI tool (due to #107 I'm guessing?) and that leads to the error `_hishtory_precmd:8: command not found: hishtory` in your shell? 

Generally, in situations where you want to disable or uninstall hishtory, I reccomend either:

* Running `hishtory disable` to temporarily disable hishtory (which is enough to work around the problems in #107)
* Running `hishtory uninstall` to fully uninstall hishtory (which will clean up all the relevant files and prevent this error)

In your situation, you can fix this by either:

* Manually editing your `~/.zshrc` file to remove the lines referencing hishtory
* Installing hishtory again, and then running `hishtory uninstall`

Also, I'd like to just point out that #107 has been fixed, so if that is your only issue, you should be able to just reinstall hishtory and pick up where you left off. :)

**Comment by greatbooms** [comment]
![image](https://github.com/ddworken/hishtory/assets/5744408/d774e578-bc1f-4ad1-9080-74cdd2ca7468)
Sorry about that.

I didn't see the part about restarting!

I restarted the terminal and it works fine!

**Comment by ddworken** [comment]
Ah, glad to hear it! If you run into any other issues, please let me know. And I hope you give hishtory another shot now that #107 has been thoroughly fixed. :)
