### ISSUE TITLE
"command not found" after apparently successful install in bash 5.1.8 on Mac OS

### ISSUE THREAD

**Issue by yukster** [ddworken/hishtory#14]
I ran the install script in the readme and got what appeared to be successful output (setting secret key, importing history, imported 500 entries, usage instructions). But when trying to run `hishtory query` I get command not found, even in a new terminal window. This is while running bash 5.1.8 on Mac OS Catalina. Once I switched to fish, it works though. Just too old a version of bash?

**Comment by alanivey** [comment]
Same, I ran `find ~ -name '*hishtory*'` and only found the imported history DB and config at `~/.hishtory`. I run bash 5 (via brew), not zsh, on macOS Ventura. I had to move `/tmp/hishtory-client` to `$HOME/.local/bin/hishtory`. Then, I found that `~/.zshrc` and `~/.bashrc` had the hishtory additions, but bash in macOS has always used `~/.bash_profile`. I copied the following into `~/.bash_profile` and I was good to go:

```bash
# Hishtory Config:
export PATH="$PATH:$HOME/.hishtory"
source "$HOME/.hishtory/config.sh"
```

The install script should use `.bash_profile` instead of `.bashrc` if the detected operating system is Darwin/macOS. I'm not sure why the binary never made it out of `/tmp`.

**Comment by ddworken** [comment]
Huh, interesting thank you for digging into this! Interestingly on my Mac I have it in `~/.bashrc` (for bash 5 from brew) and it works. And ditto for the tests on github actions. I'll have to dig up another mac to test this and dig deeper.

**Comment by ddworken** [comment]
Ah, [this](https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc) has the details. Turns out it is a weird quirk of Mac's default terminal which I missed since:

* I used iTerm2
* My tests execute in actions and not via a GUI terminal 

So I agree, this should be fixed. Digging into how to do this...

**Comment by ddworken** [comment]
Fixed by c1d17842c4b64df3e3f3e93e107d6001539a8e96 and released in v0.169. I tested it in the default terminal with bash 5.2 on MacOs. Please run `hishtory update` to get the latest version and let me know if you run into any other issues.

**Comment by alanivey** [comment]
Nice, thanks David!

**Comment by yukster** [comment]
Wow, awesome turnaround time. Thanks!
