### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by richjames0** [ddworken/hishtory#165]
I notice that the current build, using make, seems hard-coded to a certain environment (e.g. server name and username). It's also a little heavyweight for hacking around and checking things do/don't work (Docker, etc.) If it's possible to build outside of this environment would it be possible to get some minimal build instructions in the README? I ask because I'd like to make a change to the client to support specifying server port (similar to the change I made on the server side) but don't want to just throw something at you that may or may not even build :D

**Comment by ddworken** [comment]
Thank you! It is true that things are currently a bit hard-coded, and in all honesty, even I can't actually run all of the tests on my local machine (since there are *a lot* of integration tests that cover all kinds of complex scenarios). But I definitely agree and welcome all contributions so I added some info to the README to help with this. But also, feel free to just open a PR and let Github Actions run and that works great for me. :) 

Please let me know if there is anything else I can help answer!

**Comment by richjames0** [comment]
Ah fantastic - thank you David! I'll get back on this next weekend :)

**Comment by ddworken** [comment]
Sounds great! I'll go ahead and mark this as closed, but please re-open it if there is anything else I can help document.
