### ISSUE TITLE
Mac: cmd+v (paste) unreliable in Terminal and iTerm

### ISSUE THREAD

**Issue by Tuinslak** [ddworken/hishtory#185]
Seems like pasting (cmd+v) works very unreliably in both iTerm and Terminal. 

It causes the TUI to randomly crash/close or won't paste at all (need to backspace a few times and then paste for it to work). Not entirely sure what's causing this.

I can provide a screen recording if it helps? 

Using ZSH.

**Comment by ddworken** [comment]
Thanks for filing this! I took a look and I can also reproduce this (though it seems to be flaky). From my preliminary investigation, it seems to be somewhere else in the stack since hishtory never receives any pasted input nor any indication that paste was triggered. I'll keep digging into this. :)

**Comment by ddworken** [comment]
Actually, a little more investigation made me realize 7ae9f15b2925590f83af44e8039a94996f7bbc9a seems to fix this. I'm running it through tests on GH actions and will spend a bit more time validating it before I release this change, so I'll re-ping this issue once it has been released.

**Comment by ddworken** [comment]
Ok, this has now been released if you run `hishtory update`. If you run into any more issues, please reopen this issue so I can take another look!
