### ISSUE TITLE
feature: add vim bindings

### ISSUE THREAD

**Issue by busla** [ddworken/hishtory#190]
It would be great for us transitioning from `fzf` to get the following features:

1. VIM bindings for item navigation
2. Override item navigation`hishtory` keybindings.

**fzf bindings:**
- `ctrl+k`: up
- `ctrl+j`: down

Since `hishtory` binds `ctrl+k` to _delete item_, overriding that would be a requirement for adopting VIM bindings.

related: https://github.com/ddworken/hishtory/issues/55

**Comment by ddworken** [comment]
Thanks for filing this! The core code for this is actually already in place since we already [use a keymap to store configurable key bindings](https://github.com/ddworken/hishtory/blob/master/client/tui/tui.go#L45-L63), it just isn't wired up to the config to enable actually customizing this. I'll try to take this on relatively soon, but if anyone is looking to make a contribution, I think this could be a good starter one. :)

**Comment by ddworken** [comment]
This is now fully released and available, if you run `hishtory update` you can now customize the key bindings. Check out the README for information on how to do this. If you run into any issues, please re-open this issue to let me know. :)
