### ISSUE TITLE
Rendering is wrong when tab `\t` is in the command

### ISSUE THREAD

**Issue by zhou13** [ddworken/hishtory#225]
When tab `\t` is in the command, it seems that sometimes history does not compute the line width correctly, causing weird rendering issues (some lines occupy more than one line).
![Untitled](https://github.com/ddworken/hishtory/assets/576382/bd3faed9-65c4-4335-aa9e-944d4314e1c7)

**Comment by ddworken** [comment]
Ah, thank you for this bug report! 

You're exactly right that this is a bug and it explains something I've run into before but had never been able to track down. The root cause is that the `runewidth` library [defines the width of a tab as 0](https://github.com/mattn/go-runewidth/issues/77). It looks like there are some [clever ways of checking the width of a tab character](https://unix.stackexchange.com/questions/582739/how-to-know-current-tab-width-of-terminal) that we could implement. 

I'll have to experiment with this, but this will be the next thing on my todo list. So thank you!

**Comment by zhou13** [comment]
How about just replacing tab with a single space when displaying?
