### ISSUE TITLE
Shell spammed with errors when not connected to self-hosted backend

### ISSUE THREAD

**Issue by matthewcmead** [ddworken/hishtory#30]
When the backend is offline or unreachable, every shell command invoked yields a spam message to the shell about a timeout on connect.  From the blog post (https://blog.daviddworken.com/posts/hishtory-explained/), I would have expected this to fail silently since there is the presumption of loss of connectivity at times.

See the example below:
 2022/11/14 11:55:29 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:426: failed to POST /api/v1/submit?source_device_id=<devid>: Post "http://aa.bb.cc.dd:8080/api/v1/submit?
source_device_id=<devid>": dial tcp aa.bb.cc.dd:8080: connect: operation timed out

Let me know if I should do something differently.

For reference, I'm self-hosting this in a docker container reached only by tailscale.

**Comment by ddworken** [comment]
Ah thank you for this! Fixed in a18d444d098f08371f48284df109f5980afaea66. The annoying bit is that I don't have a perfect way of detecting network failures, so I have a list of errors that I know can happen. Added this one to the list. 

And please let me know how the self hosting goes! I hope it works well for you. :)

**Comment by matthewcmead** [comment]
It's working great, so far.  This is a really nice tool!

I've not been "network far" yet, but the connectivity through tailscaled with its userspace networking in the container to hishstory-server works great.  I have an open PR that shows what I've done to host this on a sqlite backend vice postgresql since I wanted this to run on minimal hardware.

**Comment by RichyHBM** [comment]
Is it possible this bug has been regressed? I'm seeing the following under the same circumstances as described originally, though the error looks to originate from a different file now

`2023/09/12 19:17:21 hishtory v0.208 fatal error at github.com/ddworken/hishtory/client/cmd/saveHistoryEntry.go:98: failed to POST /api/v1/submit?source_device_id=xxx: Post "http://127.0.0.1:11155/api/v1/submit?source_device_id=xxx": dial tcp 127.0.0.1:11155: connect: connection refused`

**Comment by ddworken** [comment]
Thanks for the comment! d4e01ce improves upon this so that this error will be detected as being due to a failed connection. This will be included in the next hiSHtory release (which I expect to do within a few days). Until then, feel free to just clone this repository and then `go build; ./hishtory install` to run the latest version of this code.
