### ISSUE TITLE
search query contains unknown search atom reserver

### ISSUE THREAD

**Issue by grosser** [ddworken/hishtory#40]
```
2022/11/26 23:04:21 hishtory fatal error at github.com/ddworken/hishtory/client/cmd/query.go:46: search query contains unknown search atom reserver
```

... idk how I caused this, was selecting an old item and it failed 🤷 
some more output on what exactly it saw would be nice

```
hiSHtory version v0.183
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
```

**Comment by grosser** [comment]
same as https://github.com/ddworken/hishtory/issues/37
... it should complain when launched with a old shell version ?

**Comment by ddworken** [comment]
Ah, I believe this is actually different from #37. I believe the issue here is that you tried to search for something like `reserver:`. hiSHtory interpreted this as using a search atom trying to match the column named `reserver` when in reality I believe you intended to search for the full string `reserver:`. 

This does seem like something worth supporting, but I do still want to warn users if they are attempting to use a search atom for a typo-ed column name. I'll work on a PR to improve this. :)
