### ISSUE TITLE
searching anything with `:` results in warning

### ISSUE THREAD

**Issue by grosser** [ddworken/hishtory#45]
maybe expected, but I'm using it to search for `sfn:generate` and got this warning instead
```
Warning: failed to search: search query contains unknown search atom sfn


Search Query: > sfn:gen
```

**Comment by ddworken** [comment]
Yeah, this is WAI. The core of the issue is that I want to:

1. Warn people if they typo column names to avoid user confusion. For example, if someone searches for `comand:foo` I'd like to warn them that this doesn't match the `command:` search atom. 
2. Support searches that contain colons for exactly the use case you've brought up (and in #40)

And 1 and 2 conflict with each other. So the best solution I can think of is to just display the warning. WDYT? Do you see a better option here?

**Comment by grosser** [comment]
warning is fine ... maybe allow "foo:bar" syntax to avoid the warning
