### ISSUE TITLE
Fatal error: failed to retrieve history entries that haven't been uploaded yet: DB query error: database is locked 

### ISSUE THREAD

**Issue by tianshuo** [ddworken/hishtory#52]
2022/12/13 16:33:33 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:29: failed to retrieve history entries that haven't been uploaded yet: DB query error: database is locked (261)

**Comment by ddworken** [comment]
Hi! Is this a persistent issue for you, or was this a one-off? And what version of hiSHtory are you runnning (you can check via `hishtory status`). I suspect this is due to an already fixed bug where hiSHtory wasn't properly enabling [WAL mode](https://www.sqlite.org/wal.html) so if you run `hishtory update` it should fix this.

**Comment by ddworken** [comment]
Closing. If you run into this again, please reopen this issue!
