### ISSUE TITLE
Conflicts with current Bash config and FZF when run in tmux

### ISSUE THREAD

**Issue by dkvasnicka** [ddworken/hishtory#53]
When I open a new terminal window after installation everything works well - colored prompt looks like always, FZF keeps Ctrl-T binding, hiSHtory takes over the Ctrl-R binding. But when I hop into a tmux session my colored prompt is gone, Ctrl-T does not invoke FZF, only Ctrl-R works - as if hiSHtory took over everything. But as I mentioned outside of tmux the world is still normal.

Any idea what could cause this? Other than that, neat tool!!

**Comment by dkvasnicka** [comment]
Killing the tmux server and starting fresh does not help.

**Comment by ddworken** [comment]
I'm guessing you're using bash on a mac? I suspect this is due to [this quirk of bash on mac](https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc). 

Where are you sourcing [fzf's `key-bindings.bash`](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash)? I'm guessing it is only sourced in `~/.bashrc`? In that case, if you also source it in `~/.bash_profile` (before the hishtory config) it should work (at least this made it work in tmux for me).

**Comment by ddworken** [comment]
I believe that 8422aa21dbe47c92b66a2a40af3d8bef3bfc6534 fixed this for new users. If you're still having this issue, see the previous comment for how to fix this. Please reopen if anyone is running into this with a fresh install.
