### ISSUE TITLE
Possible memory leak in server

### ISSUE THREAD

**Issue by Janhouse** [ddworken/hishtory#62]
I finally updated my monitoring tools and noticed that hishtory server container memory usage had increased to 4GB (1 day since reboot).

I was running a bit older version but after updating hishtory, the memory usage is still constantly rising without actively using terminal.

Have you noticed anything similar with your hosted instances?

![image](https://user-images.githubusercontent.com/1036439/208740837-8e25beb0-b686-41d1-a624-fd28fbf9b593.png)

**Comment by Janhouse** [comment]
Never mind, it went down. I guess it was fixed at some point.
![image](https://user-images.githubusercontent.com/1036439/208772589-61ffaea3-148c-45c1-8903-7b9de508a543.png)

**Comment by Janhouse** [comment]
Although, it doesn't look too good. Without doing anything it goes up and is not able to free all of it.
![image](https://user-images.githubusercontent.com/1036439/208861769-5eb87787-e0ed-4211-b2f2-95ab68b6aac8.png)

**Comment by ddworken** [comment]
Thank you for reporting this! I was having the same behavior in the server instance I run. I believe f502cbee1dbbac4f089cc6b1fe62392180c80ed7 should fix this by closing the resp when the server makes HTTP requests. I'm going to give it a couple more days of this running in my instance before marking this as closed, but I'm reasonably confident this is the root cause. :)

**Comment by Janhouse** [comment]
That helped. 
![image](https://user-images.githubusercontent.com/1036439/209447702-c39ee3ea-d511-441d-9b2a-3fc83a835554.png)

**Comment by ddworken** [comment]
Thank you for confirming! I checked and this seems stable on my end too. Glad that this is fixed. :)
