### ISSUE TITLE
Show the total number of stored commands in the CTRL+R TUI

### ISSUE THREAD

**Issue by d4v3y0rk** [ddworken/hishtory#77]
It would be nice to be able to see how many total commands have been stored in the database from the various machines.

**Comment by ddworken** [comment]
I'm not sure this is necessary to show in the main TUI since it isn't that useful. But if you want to see this, you can just run `hishtory export | wc -l`. This way you can also calculate your own stats easily (e.g. `hishtory export | cut -d ' ' -f 1 | sort | uniq -c | sort -nr`). Does that work for you?

**Comment by d4v3y0rk** [comment]
Ultimately all I wanted to know was how many entries were stored, so this is perfect.
