### ISSUE TITLE
NetBSD binary

### ISSUE THREAD

**Issue by cromedome** [ddworken/hishtory#87]
Would you kindly consider adding a NetBSD binary to the releases page?

Thanks!

**Comment by ddworken** [comment]
Sure! ac5131f adds the NetBSD binary. Though the same caveat applies for the NetBSD binary as does for the OpenBSD binary: Since Github Actions doesn't support running tests, it is not fully supported and automatic updates won't work. But if you download it from the releases page and run `./hishtory install` it should install just fine and work. :)

**Comment by cromedome** [comment]
Thank you, you're awesome :)
