### ISSUE TITLE
Inconsistent query results between two hosts

### ISSUE THREAD

**Issue by thespad** [ddworken/hishtory#90]
I have two hosts, `host1` and `host2` both running hishtory (v0.208), and both configured with the same secret key.

From host1 (the first host setup) when I Ctrl+R and enter `hostname:host2` I don't get any results other than the pre-hishtory history data, the `init` command, and the 5 following commands (which at this point are all over 24 hours ago). Its own history is fine and all visible up to date.

From host2 when I Ctrl+R and enter `hostname:host1` I get the up to date results for host1. Its own history is *also* fine and all visible up to date.

Both hosts are Ubuntu 22.04, amd64, using bash.

If it makes a difference, I'm running against a locally-hosted server instance.

**Comment by ddworken** [comment]
Thanks for the comment! I've made some recent improvements to the syncing algorithm, so if you run `hishtory reupload` on both machines, it should get them in sync again. If this happens in the future, you can run `hishtory status -v` which will tell you if syncing is currently working (or if it is broken, e.g. due to your locally-hosted server going down).
