### ISSUE TITLE
.bash_history import failing

### ISSUE THREAD

**Issue by disaac** [ddworken/hishtory#93]
Currently when attempting to import my existing .bash_history file I receive the following error

```bash
cat ~/.bash_history | hishtory import
2023/06/13 10:15:55 hishtory v0.208 fatal error at github.com/ddworken/hishtory/client/cmd/import.go:19: failed to parse bash history: bufio.Scanner: token too long
```
**.bash_history notes**

* file was successfully imported by atuin
* file is 1098573 lines long
* initially timestamps were not enabled on history but were later added so beginning entries do not have a comment with epcoh timestamp above them.
* Import failed in initial install and after attempting again via piping file to hishtory import. Same error seen in both cases. 
* longest line in file is 340810 characters
```
gwc -L ~/.bash_history 
340810 ~/.bash_history
```

**Comment by ddworken** [comment]
Thanks for the detailed bug report! That is quite the long command you have in your shell history. 1c45705 fixes this specific erro by incrementing `maxSupportedLineLengthForImport` from 256KB to 512KB. Even with this change, I suspect that importing may still fail since you have so many entries, so I'll leave this issue open so I can spend some time writing a benchmark/stress test for importing (and as part of that, I'll likely convert importing so that it operates on a streaming basis).

**Comment by ddworken** [comment]
With the three changes attached to this issue, import performance has been significantly improved. On my laptop hishtory can now import 100k entries in ~7 seconds. With 1 million entries this would still be pretty slow, so I'll look into adding a progress bar that can be displayed in cases like this.

**Comment by ddworken** [comment]
We now have a progress bar that can be used to monitor progress when importing, so I'm going to close this out. If anyone is still finding import performance to be a limiting issue, please reopen this!
